version: '3.2'
services:
  mlflow:
   image: mlflow
   ports:
     - 5000:5000
   environment:
     - MLFLOW_S3_ENDPOINT_URL=https://minio:9000
     - AWS_ACCESS_KEY_ID=testtesttest
     - AWS_SECRET_ACCESS_KEY=testtesttest
   entrypoint: bash -c "mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://mlflow/ --host 0.0.0.0"
   volumes:
     - C:\Users\user\.ssh\Project\docker\mlflow:\mlflow
  minio:
     image: minio/minio
     ports:
         - "9000:9000"
         - "9001:9001"
     command: server/data --console-address ':9001' --address ':9000'
     environment:
         - MINIO_ROOT_USER=testtesttest
         - MINIO_ROOT_PASSWORD=testtesttest
     volumes:
         - minio_data:/data
